# Belongs in .github directory of repository

name: Python application

on:
  workflow_call:
    branches: ["main"]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Style checker and error checking with flake8
      run: |
        # Python syntax errors, undefined names, PEP8
        flake8 . --count --select=E,F63,F7,F82 --extend-ignore=E226 --max-line-length=127 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --extend-ignore=W291,W292,W293,E226 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
